// Copy for the per-tool landing pages (one URL per tool, built by scripts/site.mjs).
// Every page targets the question people actually type into a search engine.
// Keep it in plain English for non-technical readers; no em-dashes.

export const SITE_URL = "https://x-utils.com";

export const TOOL_PAGES = [
  {
    slug: "non-followers",
    tool: "non-followers",
    group: "relationships",
    title: "See who does not follow you back on X (Twitter), free",
    h1: "See who does not follow you back on X (Twitter)",
    description: "Free non-followers check for X (Twitter): every account you follow that does not follow you back, with how big and how old each one is. Runs in your browser, no password, no paid API.",
    lead: "Every account you follow that does not follow you back, in one sortable table, with how big and how old each account is. The same thing the paid \"unfollowers\" apps sell, without giving anyone your password.",
    needs: { label: "your following list", url: "x.com/yourname/following" },
    time: "1 to 3 minutes for a few hundred accounts. Beyond a thousand, X pauses the list now and then; the tool waits and resumes on its own.",
    bullets: [
      "The list of accounts you follow that do not follow you back, with follower count, following count, posts, join date and bio.",
      "Your mutuals in a second table, so you can see the whole picture.",
      "Quick filters such as \"10k+ followers\", \"under 100 followers\", \"verified\" and \"joined this year\".",
      "A \"Copy handles\" button for the rows you are looking at, a CSV for spreadsheets and a share image.",
    ],
    sample: "docs/examples/non-followers.html",
    screenshot: "report-non-followers",
    faqs: [
      ["Does it unfollow anyone?", "No. It only reads your following list and writes a report. Unfollowing stays a decision you make yourself, one account at a time, on X."],
      ["Why do some rows show less detail than others?", "X loads the first screen of the list before the script starts. The tool asks X for that page again; when X refuses, those rows keep only the name and handle."],
      ["Can I run it on someone else's account?", "Only on a following list you can see. Public accounts work; the report then compares that account's following with its followers as X shows them to you."],
    ],
    related: ["fans", "who-unfollowed-me", "inactive-following"],
  },
  {
    slug: "fans",
    tool: "fans",
    group: "relationships",
    title: "Who follows you that you do not follow back on X (Twitter)",
    h1: "Who follows you that you do not follow back",
    description: "Free fans check for X (Twitter): the accounts that follow you without you following back, with size, age and bio, so you can decide who deserves a follow back.",
    lead: "Your followers that you do not follow back, ranked and filterable. Useful when you want to follow back real people and skip the rest.",
    needs: { label: "your followers list", url: "x.com/yourname/followers" },
    time: "1 to 3 minutes for a few hundred followers. X limits how fast followers can be read: with thousands, expect pauses of several minutes, handled automatically.",
    bullets: [
      "Every follower you do not follow back, with follower count, posts, join date and bio.",
      "Filters for size and age, so a quick scan separates real people from empty accounts.",
      "\"Copy handles\" for the rows you keep, plus CSV and a share image.",
    ],
    sample: null,
    screenshot: null,
    faqs: [
      ["Why does it say the list is partial?", "X only serves a limited number of follower pages per quarter hour. The tool waits for the reset X announces and continues; if you stop it early, the report says how many followers it saw out of the total."],
      ["Does it follow anyone back?", "No. Every x-utils tool only reads. Following back is up to you."],
    ],
    related: ["non-followers", "fake-followers", "who-unfollowed-me"],
  },
  {
    slug: "who-unfollowed-me",
    tool: "followers-diff",
    group: "relationships",
    title: "Who unfollowed me on X (Twitter): free unfollower tracker",
    h1: "Who unfollowed me on X (Twitter)",
    description: "Free unfollower tracker for X (Twitter): run it today and again later to see who unfollowed you, who is new and who changed their name, with a follower trend chart. No password, no paid API.",
    lead: "Run it today, run it again next week: who left, who is new, who changed their name, and a chart of your follower count over time. Snapshots stay in your browser, nothing is uploaded.",
    needs: { label: "your followers list", url: "x.com/yourname/followers" },
    time: "1 to 3 minutes per run for a few hundred followers; longer lists pause and resume automatically. The first run only saves a snapshot, the comparison starts with the second.",
    bullets: [
      "Accounts that unfollowed you since the last run, and new followers, in separate tables.",
      "Accounts that changed their handle, matched by their permanent id so they are not counted as lost and new.",
      "A trend chart built from every snapshot taken in this browser.",
      "A partial list is never saved as a baseline, so a rate-limited run cannot invent hundreds of \"unfollowers\".",
    ],
    sample: "docs/examples/followers-diff.html",
    screenshot: "report-followers-diff",
    faqs: [
      ["Where are the snapshots stored?", "In your browser's local storage for x.com, on this computer only. Clearing site data for x.com deletes them."],
      ["Why did the first run show no changes?", "There was nothing to compare with yet. The first run saves your followers; the differences appear from the second run on."],
      ["Can it tell me who unfollowed me before I started?", "No. X does not expose that history, so the tool can only compare snapshots it took itself."],
    ],
    related: ["non-followers", "fans", "fake-followers"],
  },
  {
    slug: "fake-followers",
    tool: "follower-quality",
    group: "relationships",
    title: "Fake follower check for X (Twitter), free bot detector",
    h1: "How many of your X (Twitter) followers are fake?",
    description: "Free fake follower audit for X (Twitter): every follower scored with transparent bot signals (default avatar, no posts, brand-new account, follows thousands) and the suspicious ones listed first, with reasons.",
    lead: "Every follower scored with simple, transparent signals: default avatar, no posts, account created this month, follows thousands and is followed by nobody. Suspicious accounts come first, and each one says why.",
    needs: { label: "your followers list", url: "x.com/yourname/followers" },
    time: "1 to 3 minutes for a few hundred followers. X limits how fast followers can be read: with thousands, expect pauses of several minutes, handled automatically.",
    bullets: [
      "A score per follower and the reasons behind it, so you can disagree with any of them.",
      "Your audience by size: how many of your followers are tiny, medium and large accounts.",
      "Filters for score, \"never posted\", \"default avatar\" and \"joined this month\".",
      "CSV export of the full scored list.",
    ],
    sample: "docs/examples/follower-quality.html",
    screenshot: "report-follower-quality-dark",
    faqs: [
      ["Is a high score proof that an account is a bot?", "No. It means the account looks like many bots do: no avatar, no posts, brand new, follows a lot. Real people sometimes look like that too, which is why every reason is shown."],
      ["Does it remove or block anyone?", "No. It reads and scores. What you do with the list is yours to decide; the blocked and muted export exists if you want a backup of what you block."],
    ],
    related: ["fans", "who-unfollowed-me", "blocked-muted-export"],
  },
  {
    slug: "inactive-following",
    tool: "inactive-following",
    group: "relationships",
    title: "Find inactive accounts you follow on X (Twitter)",
    h1: "Which accounts you follow have stopped posting?",
    description: "Free check for X (Twitter): the accounts you follow that have not posted in months, or ever, with the date of their last post. Clean up your timeline without guessing.",
    lead: "Accounts you follow that have not posted in months, or ever, with the date of their last post. By default it checks only the ones that do not follow you back, which is where most dead accounts hide.",
    needs: { label: "your following list", url: "x.com/yourname/following" },
    time: "Slower than the others: X allows about 50 profile checks every 15 minutes, so 200 accounts take about an hour with automatic pauses. The panel shows an honest estimate before it starts.",
    bullets: [
      "The last post date of each account checked, and how many months of silence that is.",
      "Silent accounts first, so the list is useful even if you stop it early.",
      "Pinned posts are ignored: a pinned post from 2019 does not make an account look alive.",
      "Change one setting in the script to check everyone you follow, not only the non-followers.",
    ],
    sample: null,
    screenshot: null,
    faqs: [
      ["Why is it so slow?", "Each account needs one look at its timeline, and X allows roughly 50 of those per quarter hour. The tool paces itself, waits when X asks, and shows the remaining time."],
      ["Does it unfollow the inactive accounts?", "No. You get the list and decide. A bulk unfollow tool is not part of x-utils because a mistake there cannot be undone."],
    ],
    related: ["non-followers", "who-unfollowed-me", "fans"],
  },
  {
    slug: "blocked-muted-export",
    tool: "blocked-muted-export",
    group: "relationships",
    title: "Export your blocked and muted accounts from X (Twitter)",
    h1: "Export your X (Twitter) block list and mute list",
    description: "Free export of your blocked and muted accounts on X (Twitter), as a report and a CSV, so your block list exists somewhere X cannot take away.",
    lead: "A copy of every account you have blocked or muted, as a readable report and a spreadsheet. X does not offer this download; now you have it.",
    needs: { label: "your blocked accounts page (or the muted one)", url: "x.com/settings/blocked/all" },
    time: "Under a minute for most people.",
    bullets: [
      "Handle, name and profile link of every blocked or muted account.",
      "Works on both pages: run it on x.com/settings/blocked/all and again on x.com/settings/muted/all.",
      "CSV and JSON, ready for a backup folder.",
    ],
    sample: null,
    screenshot: null,
    faqs: [
      ["Can it import a block list?", "Not in this version. Every tool here only reads. An import tool with a mandatory preview is on the list for a later batch."],
    ],
    related: ["fake-followers", "list-members-export", "non-followers"],
  },
  {
    slug: "engagement-report",
    tool: "engagement-report",
    group: "content",
    title: "Free X (Twitter) engagement report: your best posts and best time to post",
    h1: "Which of your X (Twitter) posts actually work?",
    description: "Free engagement report for any X (Twitter) profile: posts ranked by likes, views and engagement rate, a heatmap of the hours and weekdays that perform best, and charts you can hover. No analytics subscription needed.",
    lead: "Your posts ranked by likes, views and engagement rate, a heatmap of when your posts perform best, and per-post charts you can hover. Works on any public profile, not only your own.",
    needs: { label: "a profile page", url: "x.com/yourname" },
    time: "2 to 5 minutes for the last 300 posts. If X stops serving the timeline, the tool asks for the remaining pages directly and shows its progress.",
    bullets: [
      "Engagement rate per post: likes, reposts, replies and quotes divided by views.",
      "A heatmap of average interactions by weekday and hour, in your local time, with your best slot highlighted.",
      "Top 10 posts as reading cards, and every post in a sortable table with filters such as \"10k+ views\" and \"engagement over 2%\".",
      "A share image with the headline numbers, and a CSV for your own analysis.",
    ],
    sample: "docs/examples/engagement-report.html",
    screenshot: "report-engagement",
    faqs: [
      ["How is the engagement rate calculated?", "Likes plus reposts plus replies plus quotes, divided by the post's views, per post. The headline figure is the median across posts, so one viral post does not distort it."],
      ["Why are replies not counted as posts?", "On the Posts tab X hides replies, and so does the report. Open the profile's Replies tab and run the tool there to include them."],
      ["Why fewer posts than the profile counter says?", "The counter counts replies and reposts too. The report says how many posts it collected and what it left out, and if X cut the timeline short it says that as well."],
    ],
    related: ["thread-unroll", "bookmarks-export", "search-export"],
  },
  {
    slug: "bookmarks-export",
    tool: "bookmarks-export",
    group: "content",
    title: "Export your X (Twitter) bookmarks, free",
    h1: "Export your X (Twitter) bookmarks",
    description: "Free bookmarks export for X (Twitter): every bookmarked post as a readable page with media and numbers, a Markdown file for your notes app and a CSV. No API, no password.",
    lead: "Every bookmark as a readable page with the images, a Markdown file for Notion or Obsidian, and a spreadsheet. Your reading list, finally outside of X.",
    needs: { label: "your bookmarks page", url: "x.com/i/history" },
    time: "About a minute per few hundred bookmarks.",
    bullets: [
      "Author, date, text, media and numbers for every bookmark, newest first as X shows them.",
      "Markdown with one entry per post, ready for a notes app.",
      "CSV and JSON with links back to the original posts.",
    ],
    sample: "docs/examples/bookmarks-export.html",
    screenshot: "report-bookmarks",
    faqs: [
      ["My bookmarks are at a different address", "X moved bookmarks to x.com/i/history in 2026. Both that page and the old x.com/i/bookmarks work with the tool."],
      ["Are images downloaded?", "The report links to the images on X's servers and shows thumbnails. The files themselves are not copied."],
    ],
    related: ["likes-export", "thread-unroll", "search-export"],
  },
  {
    slug: "likes-export",
    tool: "likes-export",
    group: "content",
    title: "Export your X (Twitter) likes, free",
    h1: "Export the posts you liked on X (Twitter)",
    description: "Free likes export for X (Twitter): every post you liked as a readable page, a Markdown file and a CSV, with links back to the originals.",
    lead: "Everything you liked, as a readable page, a Markdown file and a spreadsheet. Handy before cleaning up, or just to find that post again.",
    needs: { label: "your likes page", url: "x.com/i/history/likes" },
    time: "About a minute per few hundred likes.",
    bullets: [
      "Author, date, text, media and numbers for every liked post.",
      "Markdown for your notes app, CSV and JSON for everything else.",
    ],
    sample: null,
    screenshot: null,
    faqs: [
      ["Can I export someone else's likes?", "No. X stopped showing other people's likes in 2024, so only your own likes page exists."],
    ],
    related: ["bookmarks-export", "engagement-report", "thread-unroll"],
  },
  {
    slug: "thread-unroll",
    tool: "thread-unroll",
    group: "content",
    title: "Thread unroller for X (Twitter), free",
    h1: "Read a whole X (Twitter) thread as clean text",
    description: "Free thread unroller for X (Twitter): open any post of a thread, run the tool, and get the whole thread as clean text, a readable page and a Markdown file.",
    lead: "Open any post of a thread and get the whole thread as one clean text, a readable page and a Markdown file. No bot to mention, nothing posted on your behalf.",
    needs: { label: "any post of the thread", url: "x.com/author/status/…" },
    time: "Under a minute.",
    bullets: [
      "The author's posts in order, with replies from other people left out.",
      "Media and links kept, numbers for each post.",
      "Markdown, plain text and a readable HTML page.",
    ],
    sample: null,
    screenshot: null,
    faqs: [
      ["Which posts count as the thread?", "The author's own replies chained to the first post, plus contiguous posts by the same author shown on screen. Other people's replies are ignored."],
    ],
    related: ["bookmarks-export", "engagement-report", "search-export"],
  },
  {
    slug: "search-export",
    tool: "search-export",
    group: "content",
    title: "Export X (Twitter) search results to CSV, free",
    h1: "Export X (Twitter) search results",
    description: "Free export of any X (Twitter) search, advanced operators included, as a CSV and a readable page. Track a topic, a hashtag or mentions of your brand without the paid API.",
    lead: "Any search, including advanced operators such as from:, since: and min_faves:, as a spreadsheet and a readable page. Track a topic or your brand mentions without paying for the API.",
    needs: { label: "a search results page", url: "x.com/search?q=…" },
    time: "A minute or two, depending on how far you let it scroll.",
    bullets: [
      "Author, date, text, media, links and numbers for every result.",
      "Works with the Latest tab and with advanced operators.",
      "CSV and JSON, plus reading cards.",
    ],
    sample: null,
    screenshot: null,
    faqs: [
      ["How many results can it collect?", "As many as X keeps serving while it scrolls, a few hundred to a couple of thousand. Change the limit at the top of the script if you need more."],
    ],
    related: ["engagement-report", "list-members-export", "bookmarks-export"],
  },
  {
    slug: "list-members-export",
    tool: "list-members-export",
    group: "content",
    title: "Export the members of an X (Twitter) List, free",
    h1: "Export the members of an X (Twitter) List",
    description: "Free export of any X (Twitter) List's members, flagged with whether you follow them and whether they follow you, as a report and a CSV.",
    lead: "Everyone on a List, yours or someone else's, flagged with whether you follow them and whether they follow you. As a report and a spreadsheet.",
    needs: { label: "a List members page", url: "x.com/i/lists/…/members" },
    time: "Under a minute for most Lists.",
    bullets: [
      "Handle, name, size, bio and profile link of every member.",
      "Two flags per member: follows you, you follow.",
      "CSV for a spreadsheet or a CRM.",
    ],
    sample: null,
    screenshot: null,
    faqs: [
      ["Does it add anyone to a List?", "No. It reads the members page and writes the report. Adding members stays a manual action on X."],
    ],
    related: ["non-followers", "fans", "search-export"],
  },
];
